# Generated by Django 3.0.7 on 2020-07-06 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='client',
        ),
        migrations.AddField(
            model_name='reserva',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='client', to='core.Cliente'),
            preserve_default=False,
        ),
    ]
