# Generated by Django 3.0.7 on 2020-06-29 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primeiro_nome', models.CharField(max_length=64)),
                ('ultimo_nome', models.CharField(max_length=64)),
                ('endereco', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=32)),
                ('celular', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('detalhes', models.TextField(max_length=255)),
                ('data_cadastro', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarto', models.CharField(max_length=255)),
                ('quantidade_adulto', models.CharField(max_length=255)),
                ('quantidade_crianca', models.CharField(max_length=255)),
                ('data_ida', models.CharField(max_length=255)),
                ('data_volta', models.CharField(max_length=255)),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantidade_estrela', models.CharField(max_length=255)),
                ('cidade', models.CharField(max_length=255)),
                ('distrito', models.CharField(max_length=5)),
                ('nome_hotel', models.CharField(max_length=255)),
                ('quantidade_quarto', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_compra', models.DateField(auto_now_add=True)),
                ('preco_total', models.CharField(max_length=32)),
                ('data_pagamento', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='voo',
            old_name='qtd',
            new_name='quantidade_passagem',
        ),
        migrations.RemoveField(
            model_name='voo',
            name='companhiaIda',
        ),
        migrations.RemoveField(
            model_name='voo',
            name='companhiaVolta',
        ),
        migrations.RemoveField(
            model_name='voo',
            name='dataIda',
        ),
        migrations.RemoveField(
            model_name='voo',
            name='dataVolta',
        ),
        migrations.RemoveField(
            model_name='voo',
            name='destinoIda',
        ),
        migrations.RemoveField(
            model_name='voo',
            name='destinoSiglaIda',
        ),
        migrations.RemoveField(
            model_name='voo',
            name='destinoSiglaVolta',
        ),
        migrations.RemoveField(
            model_name='voo',
            name='destinoVolta',
        ),
        migrations.RemoveField(
            model_name='voo',
            name='origemIda',
        ),
        migrations.RemoveField(
            model_name='voo',
            name='origemSiglaIda',
        ),
        migrations.RemoveField(
            model_name='voo',
            name='origemSiglaVolta',
        ),
        migrations.RemoveField(
            model_name='voo',
            name='origemVolta',
        ),
        migrations.RemoveField(
            model_name='voo',
            name='precoTotal',
        ),
        migrations.RemoveField(
            model_name='voo',
            name='precoUnit',
        ),
        migrations.AddField(
            model_name='voo',
            name='companhia_ida',
            field=models.CharField(default=20200628, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voo',
            name='companhia_volta',
            field=models.CharField(default=20200728, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voo',
            name='data_ida',
            field=models.CharField(default=20200628, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voo',
            name='data_volta',
            field=models.CharField(default=20200728, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voo',
            name='destino_ida',
            field=models.CharField(default=20200628, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voo',
            name='destino_sigla_ida',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voo',
            name='destino_sigla_volta',
            field=models.CharField(default=2, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voo',
            name='destino_volta',
            field=models.CharField(default='sao paulo', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voo',
            name='origem_ida',
            field=models.CharField(default='rio de janeiro', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voo',
            name='origem_sigla_ida',
            field=models.CharField(default='RJ', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voo',
            name='origem_sigla_volta',
            field=models.CharField(default='SP', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voo',
            name='origem_volta',
            field=models.CharField(default='sao paulo', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voo',
            name='preco_total',
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voo',
            name='preco_unitario',
            field=models.DecimalField(decimal_places=2, default=500.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='voo',
            name='direto',
            field=models.CharField(max_length=255),
        ),
    ]
