# Generated by Django 3.0.7 on 2020-07-06 02:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='hotel',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='reserva',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='voo',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='client',
        ),
        migrations.AddField(
            model_name='reserva',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='itens_pacote',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='reserva',
            constraint=models.UniqueConstraint(fields=('id', 'customer'), name='reserva_constraint'),
        ),
    ]
