# Generated by Django 3.0.7 on 2020-07-06 05:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserva',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='customer',
        ),
        migrations.AddField(
            model_name='cliente',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='cpf',
            field=models.ForeignKey(default='11111111111', on_delete=django.db.models.deletion.CASCADE, to='core.Cliente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='hotel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Hotel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='voo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Voo'),
            preserve_default=False,
        ),
    ]
