# Generated by Django 3.0.7 on 2020-07-06 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200705_2221'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserva',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='reserva',
            name='clientes',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='core.Cliente'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='reserva',
            unique_together={('clientes', 'id')},
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='customer',
        ),
    ]
