# Generated by Django 3.0.7 on 2020-07-06 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200706_0150'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cliente',
            name='cliente_cpf_constraint',
        ),
    ]
