# Generated by Django 3.0.7 on 2020-06-29 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200628_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='id_cliente',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
