# Generated by Django 3.0.7 on 2020-07-06 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200706_0157'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='itens_reserva',
            field=models.CharField(default='seila', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(max_length=20),
        ),
    ]
