# Generated by Django 3.0.7 on 2020-07-06 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200705_2235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='clientes',
            new_name='customers',
        ),
        migrations.AlterUniqueTogether(
            name='reserva',
            unique_together={('customers', 'id')},
        ),
    ]
