# Generated by Django 3.0.7 on 2020-07-06 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200705_2237'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='hotel',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='voo',
            options={'ordering': ['id']},
        ),
        migrations.AlterUniqueTogether(
            name='reserva',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='customers',
        ),
    ]
