# Generated by Django 3.0.7 on 2020-06-26 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precoUnit', models.CharField(max_length=256)),
                ('precoTotal', models.CharField(max_length=256)),
                ('direto', models.CharField(max_length=256)),
                ('companhiaIda', models.CharField(max_length=256)),
                ('origemIda', models.CharField(max_length=256)),
                ('origemSiglaIda', models.CharField(max_length=256)),
                ('destinoIda', models.CharField(max_length=256)),
                ('destinoSiglaIda', models.CharField(max_length=256)),
                ('dataIda', models.CharField(max_length=256)),
                ('companhiaVolta', models.CharField(max_length=256)),
                ('origemVolta', models.CharField(max_length=256)),
                ('origemSiglaVolta', models.CharField(max_length=256)),
                ('destinoVolta', models.CharField(max_length=256)),
                ('destinoSiglaVolta', models.CharField(max_length=256)),
                ('dataVolta', models.CharField(max_length=256)),
                ('qtd', models.IntegerField()),
            ],
        ),
    ]
